apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sysdig-anthos
  namespace: sysdig-anthos
  labels:
    name: sysdig-anthos
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: sysdig-anthos
    spec:
      containers:
      - name: sysdig-anthos
        image: gcr.io/vibrant-tree-219615/sysdig-anthos-prod:d6924a1
        ports:
        - containerPort: 8001
